In [1]:
import pandas as pd
import os

## .csv file 전처리

In [2]:
# subj : 피실험자 번호(2~27, 21,22 없음) / trial : 시행 횟수 / level : 끈적임 레벨 / modality : 자극 방식(시각 / 촉각 / 청각) / orders : 반복 횟수
# 피실험자 당 실험 횟수 : (반복횟수) * (시행 횟수) * (자극 방식) --> 2 * 48 * 3 = 288
# 총 실험 횟수 : (피실험자 당 실험 횟수) * (피실험자 수) --> 288 * 24 = 6912

df = pd.read_csv('./bhv_data_AllinOne.csv',index_col=0)
df = pd.DataFrame(df)
df = df.drop(columns={'resp','correct','block','orders'})
modality_list = list(df['modality'].unique())
df

      subj  trial  level  modality
0        2      1      3     touch
1        2      2      4     touch
2        2      3      3     touch
3        2      4      1     touch
4        2      5      4     touch
...    ...    ...    ...       ...
6907    27     44      2  auditory
6908    27     45      1  auditory
6909    27     46      4  auditory
6910    27     47      4  auditory
6911    27     48      2  auditory

[6912 rows x 4 columns]

### 자극 level_1~4 까지 분류 .csv 파일 저장

In [3]:
# for i in range(1,5):
#     df_level = df.loc[df['level'] == i]
#     df_level.to_csv(f'./trial_level/level_{i}.csv')

### modality_touch / visual / auditory 분류 .csv 파일 저장

In [4]:
# for i in modality_list:
#     df_modality = df.loc[df['modality'] == i]
#     df_modality.to_csv(f'./trial_modality/modality_{i}.csv')

### 자극 modality 별 level 분류

In [ ]:
# for modal in modality_list:
#     df = pd.read_csv(f'./trial_modality/modality_{modal}.csv',index_col=0)
#     df = pd.DataFrame(df)
#     os.mkdir(f'./modality_per_levels/{modal}')
    
#     for level in range(1,5):
#         df_level = df.loc[df['level'] == level]
#         df_level.to_csv(f'./modality_per_levels/{modal}/{modal}_level_{level}.csv')

In [14]:
# 002_auditory_01_trial_0001_correct_beta.nii
new_df = pd.read_csv('./modality_per_levels/auditory/auditory_level_1.csv',index_col=0)
new_df = pd.DataFrame(new_df)
new_df = new_df.reset_index()
new_df.drop(columns={'index'},inplace=True)
new_df

     subj  trial  level  modality
0       2      2      1  auditory
1       2      4      1  auditory
2       2      7      1  auditory
3       2      8      1  auditory
4       2     10      1  auditory
..    ...    ...    ...       ...
571    27     33      1  auditory
572    27     34      1  auditory
573    27     39      1  auditory
574    27     41      1  auditory
575    27     45      1  auditory

[576 rows x 4 columns]